### ISSUE TITLE
Request for self contained executable of the app for including in the container image for debugging

### ISSUE THREAD

**Issue by madhub** [lowleveldesign/dotnet-wtrace#2]
Thanks for the wonderful tool , it would great if self contained executable is available that can be included in container image for debugging. This is especially useful in debugging apps deployed in Kubernetes .  
I can also create self contained app by forking the your repo, but I though it would be useful to be available in the main repo.

**Comment by lowleveldesign** [comment]
Thank you for the nice words and the suggestion. I will update the deployment very soon.

**Comment by madhub** [comment]
It is possible to add custom event source names from the command line so that we can see logs emitted by these sources .
For example we are using .NET Open Telemetry SDK, that emits logs with follow event source, it would be good we can pass this from command line for debugging.

1. "OpenTelemetry-Sdk",
2. "OpenTelemetry-Api",
3. "OpenTelemetry-Extensions-Hosting",
4. "OpenTelemetry-Instrumentation-Grpc",
5. "OpenTelemetry-Instrumentation-Http",
6. "OpenTelemetry.Extensions.Propagators"

Here is the Source code that emits https://github.com/search?q=repo%3Aopen-telemetry%2Fopentelemetry-dotnet+EventSource&type=code

**Comment by lowleveldesign** [comment]
It is possible, but would require a significant amount of work. Dotnet-wtrace supports only a limited number of events and adds rules to nicely print them.  That required a predefined event models. The providers that you listed use their own schemas and their own event format. To support them, you either need to add generic events support to dotnet-wtrace (but that could make the output less readable) or add handlers for all those specific events (a lot of work).

**Comment by lowleveldesign** [comment]
I updated the [latest release](https://github.com/lowleveldesign/dotnet-wtrace/releases/tag/6.0-3) with the new binaries. The zip files contain only executables and symbol files (not needed for running). For the second request, unfortunately, I don't have much time to work on it. But it is an interesting request and I will give it some thought in the future. Thanks.

**Comment by madhub** [comment]
> It is possible, but would require a significant amount of work. Dotnet-wtrace supports only a limited number of events and adds rules to nicely print them.  That required a predefined event models. The providers that you listed use their own schemas and their own event format. To support them, you either need to add generic events support to dotnet-wtrace (but that could make the output less readable) or add handlers for all those specific events (a lot of work).

I understand  predefined events with their  color scheme is really nice and easy to decipher source of the events. For all others types as you suggested generic model might help.

**Comment by madhub** [comment]
> I updated the [latest release](https://github.com/lowleveldesign/dotnet-wtrace/releases/tag/6.0-3) with the new binaries. The zip files contain only executables and symbol files (not needed for running). For the second request, unfortunately, I don't have much time to work on it. But it is an interesting request and I will give it some thought in the future. Thanks.

Thanks, I will check it out
