### ISSUE TITLE
self contained executable does not show all the handler options

### ISSUE THREAD

**Issue by madhub** [lowleveldesign/dotnet-wtrace#3]
As per documentation supported handler options are , but self container exe only show fewer options, See the attached image

- network   - to receive network events
- loader    - to receive assembly loader events
- gc        - to receive GC events
- aspnet    - to receive ASP.NET Core events
- efcore    - to receive EF Core events

![image](https://github.com/lowleveldesign/dotnet-wtrace/assets/8907962/6fedd232-2729-4b53-ba13-8ec53d839439)

Other question  , if I have to build the **Alpine Linux specific binary** , should I run the following command ?
```shell
dotnet publish -c release -r linux-musl-x64 --self-contained -p:PublishTrimmed=true -p:PublishSingleFile=true
```

**Comment by lowleveldesign** [comment]
What you see in the screenshot is just the default set of handlers. Please run `dotnet-wtrace --help` to see all the available handler (I need to show help when you start dotnet-wtrace with invalid parameters). By using the `--handlers` switch you may decide which handlers to enable. For example, to collect only efcore events in a process with PID 1234 you could run `dotnet-wtrace --handlers efcore 1234`.

And the publish command looks good to me!
